### ISSUE TITLE
no attribute 'BACKUP_LOCAL_DB_DIR

### ISSUE THREAD

**Issue by Mperonneau** [jonesim/django-gdrive-backup#1]
when i run "python manage.py backup_website"

i get this issue: AttributeError: 'Settings' object has no attribute 'BACKUP_LOCAL_DB_DIR'

bellow the configuration of my settings.py:
CREDENTIAL_FOLDER = os.path.join(BASE_DIR, 'credentials')
CREDENTIAL_FILES = {
    'drive': 'service-account.json',
}

BACKUP_GDRIVE_DIR = 'django_backup'
BACKUP_GDRIVE_DB = BACKUP_GDRIVE_DIR + '/db'

**Comment by jonesim** [comment]
You need to setup BACKUP_LOCAL_DB_DIR in settings to a directory/folder on your server. It dumps the database here before uploading to google drive

**Comment by Mperonneau** [comment]
Jonesim thank's a lot for your quick answer! but unfortunately an other problem occur when i run the python manage.py backup_website...

File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by jonesim** [comment]
Could be a problem with settings.json
https://github.com/jonesim/encrypted-credentials
or 
the credential key for the google service account
